apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-app
  namespace: production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: microservice-app
  template:
    metadata:
      labels:
        app: microservice-app
    spec:
      containers:
      - name: microservice-app
        image: 075008446817.dkr.ecr.ap-south-1.amazonaws.com/microservice-app:7
        ports:
        - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5